### ISSUE TITLE
Window icon documentation is unclear

### ISSUE THREAD

**Issue by JYxtr** [bevy-cheatbook/bevy-cheatbook#105]
# Issue
Because there's no way to set your window icon in Bevy, I looked for a workaround. The [cheatbook example](https://bevy-cheatbook.github.io/cookbook/window-icon.html) is the first (and best) result. The only problem is that the dependencies are not really clear to somebody just quickly glancing through it. The newest version of winit cannot be used due to a rather scary looking dependency error with Bevy, which relies on `syn = "=1.0.65"`. This is the error:
```
   Updating crates.io index
error: failed to select a version for `syn`.
    ... required by package `darling_core v0.13.0`
    ... which satisfies dependency `darling_core = "=0.13.0"` of package `darling v0.13.0`
    ... which satisfies dependency `darling = "^0.13"` of package `ndk-macro v0.3.0`
    ... which satisfies dependency `ndk-macro = "^0.3.0"` of package `ndk-glue v0.5.0`
    ... which satisfies dependency `ndk-glue = "^0.5"` of package `winit v0.26.0`
    ... which satisfies dependency `winit = "^0.26.0"` of package `charon v0.1.0 (/home/user/Repos/charon)`
versions that meet the requirements `^1.0.69` are: 1.0.82, 1.0.81, 1.0.80, 1.0.79, 1.0.78, 1.0.77, 1.0.76, 1.0.75, 1.0.74, 1.0.73, 1.0.72, 1.0.71, 1.0.70, 1.0.69

all possible versions conflict with previously selected packages.

  previously selected package `syn v1.0.65`
    ... which satisfies dependency `syn = "=1.0.65"` of package `bevy v0.5.0`
    ... which satisfies dependency `bevy = "^0.5.0"` of package `charon v0.1.0 (/home/user/Repos/charon)`

failed to select a version for `syn` which could resolve this conflict
```
Downgrading fixes that, but going to `winit = "^0.25.0"` (or anything except v0.24.0) still leaves you with the error below:
```
*[main][~/Repos/charon]$ cargo build
    Updating crates.io index
   Compiling charon v0.1.0 (/home/jy/Repos/charon)
error[E0308]: mismatched types
  --> src/main.rs:25:34
   |
25 |     primary.set_window_icon(Some(icon));
   |                                  ^^^^ expected struct `winit::icon::Icon`, found struct `Icon`
   |
   = note: perhaps two different versions of crate `winit` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `charon` due to previous error
```
At least its more helpful and points out that there's two different versions, meaning you could possibly figure out the problem with `cargo tree`. After staring at the tree output, you find out that brevy depends on winit v0.24.0 - changing your config to that fixes the problem.
### Possible resolution
The [cheatbook example](https://bevy-cheatbook.github.io/cookbook/window-icon.html) doesn't specify which winit version to use in the `Cargo.toml` and some people might benefit from not having to deal with the above errors. Simply specifying that you need winit v0.24.0 rather than v0.26.0 would ensure nobody else has to figure that out themselves

**Comment by inodentry** [comment]
Bevy 0.6 uses winit 0.26 now, but I added a note to the example, about having to make sure to use compatible versions, if such a situation happens again.
