### ISSUE TITLE
A short example of using a Resource in a system on the Resource page

### ISSUE THREAD

**Issue by speakk** [bevy-cheatbook/bevy-cheatbook#110]
Currently the Resource page shows how to create resources, and explains shortly how to use them, but also having a short example of using one would be helpful.

**Comment by inodentry** [comment]
Thanks for reporting this! This is a holdover from when the Programming chapter was still designed to be followed in-order; the expectation was that people would have just read the "systems" page, which shows how to use them.

Now that the goals of the book have changed, and it is explicitly a reference-style book where each page should be self-contained, I gotta address this (and other similar things).

I will do a proof-read of the whole chapter to see if I notice other similar issues. :)
