### ISSUE TITLE
Document pitfalls around using generic system parameters

### ISSUE THREAD

**Issue by TheRawMeatball** [bevy-cheatbook/bevy-cheatbook#112]
The immediately obvious method to build systems generic over a system param such as
```rs
fn generic_system<P: SystemParam>(param: P) {}
```
doesn't work. This is because system parameters need to be generic over two lifetimes so bevy can call it with the correct lifetimes, whereas directly using a given generic as a parameter locks it into a single type that doesn't match what bevy can give it. The solution is to "add back" the lifetimes by going through traits, such as
```rs
fn generic_system<P: SystemParam>(
    param: <P::Fetch as SystemParamFetch<'_, '_>>::Item,
) {}
```
Notes:
usually a generic system can't do much with it's generic parameter and needs to hand it over to a user-provided function. If this is implemented as one function, this can require extra bounds:
```rs
fn generic_system_builder<P, F>(func: F) -> BoxedSystem
where
    F: Send + Sync + 'static,
    F: Fn(<P::Fetch as SystemParamFetch<'_, '_>>::Item),
    for<'w, 's> <P::Fetch as SystemParamFetch<'w, 's>>::Item: SystemParam<Fetch = P::Fetch>,
    P: SystemParam,
{
    let f = move |x: Res<i32>, p: <P::Fetch as SystemParamFetch<'_, '_>>::Item| {
        dbg!(x);
        func(p);
    };
    Box::new(f.system())
}
```
Removing any of the where bounds here will cause a compile error. As for potential issues on the callsite for such a function, the parameters need to be given to the builder and cannot be inferred from the closure parameters.
```rs
// compiles
generic_system_builder::<Res<u32>, _>(|x| {});
// doesn't compile
generic_system_builder(|x: Res<u32>| {});
```

Similar patterns also used in the new renderer, with traits such as RenderCommand: https://github.com/bevyengine/bevy/blob/f5039a476d48ec19bd74c94e83e10772565c68f1/crates/bevy_render/src/render_phase/draw.rs#L132

`bevy::ecs::system` has useful type aliases for working with this pattern, such as lifetimeless versions of `Res`, `Query`, etc. and aliases for long type paths.

In the future, when rust stabilizes GAT s, all this should become *significantly* simpler

**Comment by hlb8122** [comment]
One of the reasons why people might be mislead is that the current documentation states
> Systems are functions with all arguments implementing `SystemParam`.
https://docs.rs/bevy_ecs/0.6.0/bevy_ecs/system/trait.System.html
and does not describe any further bounds.

**Comment by inodentry** [comment]
@TheRawMeatball is this still relevant now that we have GATs?

I'm going to close this issue. If you think that Cheatbook should still document something related to this, using GATs, please reopen. :)

**Comment by TheRawMeatball** [comment]
I'm pretty sure this is relevant, as even with gats, directly asking for `P` will lead to issues.
