### ISSUE TITLE
Pitfall: Forgetting to add `Transform` and `GlobalTransform` when creating hierarchies.

### ISSUE THREAD

**Issue by BGR360** [bevy-cheatbook/bevy-cheatbook#115]
I spent an uncomfortable amount of time debugging an issue that I ultimately figured out was due to me not explicitly adding a `Transform` and `GlobalTransform` component to a parent entity.

My intuition told me that calling `.with_children()` on a spawned entity would result in Bevy adding the proper `Transform`/`GlobalTransform` components to both the parent and children, but apparently this is not the case. At least, my code did not work as expected until I manually added these components to the parent.

Might be good to mention on this page: https://bevy-cheatbook.github.io/features/parent-child.html

**Comment by inodentry** [comment]
I'm pretty sure all the relevant places in the book should make readers aware of this now. I've also just added a very visible note on the parent-child page.
