### ISSUE TITLE
I'am trying to translate this book to chinese

### ISSUE THREAD

**Issue by yiv** [bevy-cheatbook/bevy-cheatbook#124]
May I have some guide how to contribute

**Comment by inodentry** [comment]
I do not accept translations.

The content of the book is changing all the time, as I am actively working on it and improving it.

If you translate the book, it would probably quickly be outdated.

If you want to have a book in Chinese, I suggest you just write/maintain/host your own book. You will be responsible for the information you write in it. Feel free to take inspiration or base it on my book as much as you want.
