### ISSUE TITLE
remove weealloc suggestion or add warning about OOM in wasm section

### ISSUE THREAD

**Issue by TomPridham** [bevy-cheatbook/bevy-cheatbook#129]
it seems like weealloc doesn't work terribly well with bevy. it grows memory at a fairly quick pace and will cause an OOM with just the basic program below.
i'm also not the only person to encounter issues with it: https://github.com/rustwasm/wee_alloc/issues/105
would you be open to a pr removing it from the wasm section or just adding a disclaimer saying that it is potentially broken?
```
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen]
pub fn run() {
    App::new()
        .add_plugins(DefaultPlugins)
        .run();
}

**Comment by inodentry** [comment]
OOF. OK, I will remove it.
