### ISSUE TITLE
set_window_icon recipe freezes the bevy app on windows

### ISSUE THREAD

**Issue by johanhelsing** [bevy-cheatbook/bevy-cheatbook#133]
I followed https://bevy-cheatbook.github.io/cookbook/window-icon.html, but that seems to freeze the bevy app. Not sure if it's a bug in winit or bevy or how it's used in the example.

It's specifically the line

```rust
primary.set_window_icon(Some(icon));
```

That seems to make everything freeze

**Comment by johanhelsing** [comment]
Seems to be racy (works maybe 1 out of 10 times)

**Comment by johanhelsing** [comment]
Making it an exclusive system seems to make it non-racy for me, i.e.:

```rust
        .add_startup_system(set_window_icon.exclusive_system())
```

Not really sure what the underlying issue is, or if that completely solves, it, but at least it seems to work for me (worked 20 times in a row).

**Comment by inodentry** [comment]
`WinitWindows` needs to be accessed from the main thread. Making the system exclusive will work, but the real fix is to use `NonSend` (Bevy had mistakenly not required it, this bug is fixed now). I have updated the info in the book, and there is now also a page about non-send resources. :)
