### ISSUE TITLE
Destructuring queries forceably moves and how to fix

### ISSUE THREAD

**Issue by CoffeeVampir3** [bevy-cheatbook/bevy-cheatbook#152]
Hi, I'm a fairly new rustacean/bevy user and I ran into a funny gotcha when attempting to iterate a collection twice. Prompted by a discussion in the bevy discord, here's an issue I ran into and how to fix it:

```rust
fn initial_collapse(
    mut entities: Query<(&GridPosition, &Entity, &mut GridState)>,
    mut text: Query<(&Entity, &mut Text)>) {
//...
    let entities_iter = entities.iter_mut();
    let text_iter = text.iter_mut();
    let iter = entities_iter.zip(text_iter);
    let k: Vec<((&GridPosition, &Entity, Mut<'_, GridState>), (&Entity, Mut<'_, Text>))> = iter.collect();
    let mut dependent_value: usize;

    for ((gpos, ent, mut gs), (tent, mut textitem)) in k {
        if ent.row == random_row && ent.col == random_col {
            dependent_value = gs.collapse();
            let a = textitem.sections.first_mut().unwrap();
            a.value = dependent_value.to_string();
        }
    }

    for ((gpos, ent, mut gs), (tent, mut textitem)) in k {
        //do things with dependent value here
    }
```

Here, k actually is moved due to the destructuring and the second pass over k is no longer possible. See error:
>>> use of moved value: k
value used here after moverustcE0382
main.rs(201, 56): k moved due to this implicit call to .into_iter()
main.rs(197, 9): move occurs because k has type Vec<((&GridPosition, &Entity, bevy::prelude::Mut<'_, GridState>), (&Entity, bevy::prelude::Mut<'_, bevy::prelude::Text>))>, which does not implement the Copy trait
collect.rs(261, 18): this function takes ownership of the receiver self, which moves k

The fix is to change the destructuring into using `ref` and `.iter_mut()`

```rust
//...
    let k: Vec<((&GridPosition, &Entity, Mut<'_, GridState>), (&Entity, Mut<'_, Text>))> = iter.collect();
    for ((ref gpos, ref ent, ref mut gs), (ref tent, ref mut textitem)) in k.iter_mut() {
        if ent.row == random_row && ent.col == random_col {
            dependent_value = gs.collapse();
            let a = textitem.sections.first_mut().unwrap();
            a.value = dependent_value.to_string();
        }
    }

    for ((ref gpos, ref ent, ref mut gs), (ref tent, ref mut textitem)) in k.iter_mut() {
        //do things with dependent value here
    }
```

Here we're able to iterate over the same query multiple times with no issues.

**Comment by inodentry** [comment]
Why are you collecting things into a temporary Vec at all? This is inefficient and unnecessary. Simply call `query.iter_mut()` in each for loop.
