### ISSUE TITLE
Chapter 9.15 (States) uses the old resource type "AppState".

### ISSUE THREAD

**Issue by AndrewCS149** [bevy-cheatbook/bevy-cheatbook#155]
In Ch 9 section 15 (States), the old resource "AppState" is being used. I believe as per Bevy 0.7, it should be "GameState". 

<img width="422" alt="image" src="https://user-images.githubusercontent.com/52691521/173978636-446e62c7-4376-442e-8904-4ad28303c6c6.png">

**Comment by inodentry** [comment]
This is not something from Bevy. Here `AppState` is the generic type representing the state. It is an enum you define in your project. It can be called whatever you want.
