### ISSUE TITLE
Ambiguity of coordinate system handedness

### ISSUE THREAD

**Issue by jshook** [bevy-cheatbook/bevy-cheatbook#156]
The statement "This is a right-handed coordinate system. You can use the fingers of your right hand to visualize the 3 axes: thumb=X, index=Y, middle=Z." does not ring true for everyone, since the shortcut has been taught in various ways depending on what disciplines you come from. Given this ambiguity, this can actually be more confusing than clarifying.

Different conventions I've seen:
* pointing forward with your index finger, away from yourself
* pointing up with your index finger, thumb towards self
* pointing up with your index finger, palm to wards self

It would be best to have a small reference graphic to illustrate the concept if you use "right handed" or "left handed".

**Comment by inodentry** [comment]
I was meaning to have a graphic for the coordinate system for a long time, I even asked Freya Holmer for permission to adapt hers ... a year or so ago. 😅 

Adding it now.
