### ISSUE TITLE
Debugging failed IntoSystem macro

### ISSUE THREAD

**Issue by alice-i-cecile** [bevy-cheatbook/bevy-cheatbook#16]
Stopgap solution for: https://github.com/bevyengine/bevy/issues/1519

IMO, the correct choice here is to have a page for "I can't add my function as a system!" or something of the like. It should explain each of the options that impl `SystemParam`, and call out common mistakes for each. As an example, missing `&mut` for `Commands`, missing `&` for components etc.

**Comment by jamadazi** [comment]
Would you be willing to help me with collecting examples of error messages to showcase?

> each of the options

Could you help me make a list?

**Comment by alice-i-cecile** [comment]
Yep, let me dig through the spaghetti that is [SystemParam](https://docs.rs/bevy/0.4.0/bevy/ecs/trait.SystemParam.html).

1. Query and QuerySet
2. QueryFilters
3. Commands
4. Res, ResMut and Local (and ChangedRes, but that's probably getting cut)

There should be a few more in 0.5: EventReader and Archetypes (and friends, coming in The PR).

**Comment by jamadazi** [comment]
I dug through it myself and managed to make a comprehensive list.

I am basically done with the page, I'll make a PR so that you can give feedback.

But first:

Could you provide a good representative example of what the "arcane compiler error" looks like?

I want to include it as a snippet so that people can know what this page refers to.

**Comment by jamadazi** [comment]
Also, what is the maximum supported number of total overall system parameters?

**Comment by alice-i-cecile** [comment]
> Also, what is the maximum supported number of total overall system parameters?

16

**Comment by alice-i-cecile** [comment]
Snippet:

```
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(malformed_system.system())
        .run();
}

struct Component;
fn malformed_system(query: Query<Component>, mut commands: Commands) {}
```

This initially results in:

```
the trait bound `Component: WorldQuery` is not satisfied
the trait `WorldQuery` is not implemented for `Component`
```

We fix that by adding a `&`:
```rs
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(malformed_system.system())
        .run();
}

struct Component;
fn malformed_system(query: Query<&Component>, mut commands: Commands) {}
```

which results in: 

```
no method named `system` found for fn item `for<'r, 's> fn(bevy::prelude::Query<'r, &'s Component>, bevy::prelude::Commands) {malformed_system}` in the current scope
`malformed_system` is a function, perhaps you wish to call it
```

and the final fixed code is:
```rs
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(malformed_system.system())
        .run();
}

struct Component;
fn malformed_system(query: Query<&Component>, mut commands: &mut Commands) {}
```

**Comment by jamadazi** [comment]
Oh! I missed the part about `Query<Component>` (without the `&`/`&mut`) being a common beginner pitfall! Thanks for pointing that out!

Thanks for the snippets, i have all the information i need now.
