### ISSUE TITLE
Update Hot-Reloading Assets page to use `AssetServerSettings`

### ISSUE THREAD

**Issue by TimJentzsch** [bevy-cheatbook/bevy-cheatbook#171]
The [Hot-Reloading Assets page](https://bevy-cheatbook.github.io/assets/hot-reload.html) currently suggests to use the following:

```rust
asset_server.watch_for_changes().unwrap();
```

The [Bevy example](https://github.com/bevyengine/bevy/blob/v0.7.0/examples/asset/hot_asset_reloading.rs) instead inserts an `AssetServerSettings` resource with `watch_for_changes: true`:

```rust
App::new()
        // Tell the asset server to watch for asset changes on disk:
        .insert_resource(AssetServerSettings {
            watch_for_changes: true,
            ..default()
        })
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
```

This seems to be easier than to define a new startup system.

**Comment by inodentry** [comment]
Done, now with proper plugin configuration for 0.9
