### ISSUE TITLE
"Logging, console messages" section should mention what plugin you need in order for logging to work

### ISSUE THREAD

**Issue by bzm3r** [bevy-cheatbook/bevy-cheatbook#184]
If you're not using `DefaultPlugins`, what plugin do you need for logging to work? I think it's the `LogPlugin`, but I'm not sure. 

I went to the bevy cheatbook page, but couldn't find any info on this.

**Comment by inodentry** [comment]
Well, since Bevy switched to doing configuration via the plugins instead of resources, it is now obvious. You can see from the code snippet that the settings are inside `LogPlugin`. That said, I added a note to the page to make it clearer.
