### ISSUE TITLE
Advice on specifying the branch of libraries via git is wrong

### ISSUE THREAD

**Issue by alice-i-cecile** [bevy-cheatbook/bevy-cheatbook#186]
On [this page](https://bevy-cheatbook.github.io/setup/bevy-git.html?highlight=bleed#should-you-use-bleeding-edge-bevy), the following line is provided:

```toml
# add any 3rd-party plugins you use, and make sure to use the correct branch
# (alternatively, you could also specify a commit hash, with "rev")
bevy_thing = { git = "https://github.com/author/bevy_thing?branch=bevy_main" }
```

This is wrong: the `?branch` part of the URL is simply ignored, and the main branch is used. Instead, you must specify `branch = "bevy_main".

**Comment by inodentry** [comment]
I've reworked that page to have less emphasis on trying to patch around plugins to get them to work, and to instead encourage users to fork things so they are in control. That said, it still has some TOML snippets to help with configuration, and I have followed your advice there. :)
