### ISSUE TITLE
Bundles are not accepted by Entity.push_children()

### ISSUE THREAD

**Issue by TheCarpetMerchant** [bevy-cheatbook/bevy-cheatbook#193]
The examples of https://bevy-cheatbook.github.io/features/parent-child.html use Bundles, but `push_children` only accepts `Entity`

**Comment by inodentry** [comment]
The code looks correct to me. Maybe you got confused.

Also, all code in the book is automatically checked for compilation errors before it goes public. If there was indeed an error with the wrong type being used in a method call, it would have been caught. :)
