### ISSUE TITLE
Common pitfall: querying for bundles

### ISSUE THREAD

**Issue by alice-i-cecile** [bevy-cheatbook/bevy-cheatbook#20]
Very common: using `Query<SpriteBundle>`, rather than asking for the component within it.

**Comment by jamadazi** [comment]
Addressed in the new 0.5 book with notes in the pages where the concepts of bundles and queries are introduced. I think this should be enough to teach new users who are learning from the book. I don't think this needs a page in "Common Pitfalls" (hopefully as it is better taught from the beginning, it won't be a "common pitfall" anymore :wink: :smile: ).
