### ISSUE TITLE
thank you very much for your book !!

### ISSUE THREAD

**Issue by syapk** [bevy-cheatbook/bevy-cheatbook#202]
so I sent you a small financial aid to motivate you to continue.
I have a readerbook is it possible to have the epub of your book?
thanks!!

**Comment by inodentry** [comment]
The book is developed using `mdbook`. A quick google search for "mdbook epub" shows this https://github.com/Michael-F-Bryan/mdbook-epub . You could try to see if you could use it to generate an epub version. I am not interested in doing that myself.
