### ISSUE TITLE
Better variable naming for example

### ISSUE THREAD

**Issue by c0wjay** [bevy-cheatbook/bevy-cheatbook#215]
https://github.com/bevy-cheatbook/bevy-cheatbook/blob/3ca27b9f62b8c25b37b62843db912824cf067b4f/src/code/src/basics.rs#L341-L349

In this section,
```rust
if let Some(mut c) = c {
    // do something
}
```
Book using `if let` patterns in unwrapping `c`,
but I think this can be confusing, especially for someone unfamiliar with Rust.
```rust
if let Some(mut unwrapped_c) = c {
    // do something
}
```
Using variable names like this seems a bit better, what do you think?

**Comment by inodentry** [comment]
While I don't think that Bevy Cheatbook should also be teaching people Rust, the accessibility of basic content like this matters. Have you (or someone you know) actually found this confusing? Or are you just assuming that people might?

**Comment by CiderSlime** [comment]
```if let``` seems to be a common construct in rust, which newbies can learn in rust book, many examples or tutorials.

**Comment by inodentry** [comment]
I would expect readers of the book to be aware of the `if let` syntax, and of "name shadowing" (that you can redefine variables with the same name) concept.
