### ISSUE TITLE
"opt-level = 1" can cause breakpoints to be ignored

### ISSUE THREAD

**Issue by roanvonb** [bevy-cheatbook/bevy-cheatbook#216]
**Section**
2.2 Slow Performance

**Content**
[profile.dev] 
opt-level = 1

**Issue**
Sometimes caused my breakpoints to be missed. 
Took me a while to figure out what was happening.

**Suggested Change:**
Note: This can omit some checks, such as debug assertions. If debugging and breakpoints are skipped over, use opt-level = 0. 

**Tools Used**
CodeLLDB and VSCode

_p.s. Thank you so much for writing this guide! I am new to both Rust and Bevy and would be so lost without it._

**Comment by inodentry** [comment]
Thank you for reporting this!

I have added a note about the degraded debugger experience with compiler optimizations.
