### ISSUE TITLE
#[bundle] no longer needed for nested bundles.

### ISSUE THREAD

**Issue by adrylain** [bevy-cheatbook/bevy-cheatbook#226]
https://bevy-cheatbook.github.io/programming/ec.html

Here in the **Component Bundles** section, `#[bundle]` is no longer needed to define a nested bundle. It can simply be removed! 

Including it now throws some errors and caused an issue with my code. 

For clarity, it should look like this instead:

    // We can nest/include another bundle.
    // Add the components for a standard Bevy Sprite:

    sprite: SpriteSheetBundle,

**Comment by inodentry** [comment]
fixed
