### ISSUE TITLE
Convert cursor to world coordinates 2d example, Window is now a component

### ISSUE THREAD

**Issue by nametable** [bevy-cheatbook/bevy-cheatbook#227]
In [Convert cursor to world coordinates](https://bevy-cheatbook.github.io/cookbook/cursor2world.html#convert-cursor-to-world-coordinates), the code example no longer works (in Bevy 0.10+) because `Windows` is no longer a `Res`, instead `Window` is a `Component` which must be queried.

There is a new example here: https://github.com/bevyengine/bevy/discussions/7970#discussioncomment-5241020

**Comment by inodentry** [comment]
Done.
