### ISSUE TITLE
Where is Windows in cursor2world.rs?

### ISSUE THREAD

**Issue by AliceMonGithub** [bevy-cheatbook/bevy-cheatbook#233]
Hello everyone! I tried to add cursor world position calculating in my game, but in 18 line i got this error

a struct with a similar name exists: `Window`rustc[E0412](https://doc.rust-lang.org/error-index.html#E0412)
main.rs(38, 18): original diagnostic
cannot find type `Windows` in this scope

Source code:
https://github.com/bevy-cheatbook/bevy-cheatbook/blob/5baa8f74860068e9d0714cd2864d4c026acccdc7/src/code/examples/cursor2world.rs

**Comment by inodentry** [comment]
Uhm that page hasn't been updated, it is still on Bevy version 0.9 as you can see in the header. I will update it now.
