### ISSUE TITLE
Inconstant / non-working code example

### ISSUE THREAD

**Issue by claudijo** [bevy-cheatbook/bevy-cheatbook#246]
The code example under the section https://bevy-cheatbook.github.io/fundamentals/visibility.html#viewvisibility says:

```
use bevy::render::view::VisibilitySystems;

app.add_systems(PostUpdate,
    debug_player_visibility
        .after(VisibilitySystems::VisibilityPropagate)
);
```

But the paragraph above the code example says "If you want to read the up-to-date value for the current frame, you should add your system to the PostUpdate schedule and order it after VisibilitySystems::CheckVisibility."

Note that the code example uses .after(VisibilitySystems::VisibilityPropagate) but the paragraph says "after VisibilitySystems::CheckVisibility".

After some experimentations I believe that the text in the paragraph is correct and the code example got it wrong.

**Comment by inodentry** [comment]
Thank you for noticing this!

The issue was that the two code snippets were swapped around. The code for the ViewVisibility section and the code for the InheritedVisibility section had swapped places. Fixed now.
