### ISSUE TITLE
Add explanation for how to setup a 2d camera in the "2d camera setup" part of the book

### ISSUE THREAD

**Issue by stevehello166** [bevy-cheatbook/bevy-cheatbook#248]
_Describe what you want to be added or changed in the book here, as a GitHub
Issue. If you have any relevant code snippets or something else you want to be
included, you can provide them._
What I want to be added is some short explanations and basic code snippets for the 2d camera setup section of the book.
For example:

_In this example a 2d camera is spawned using commands in the spawn camera function._
```
fn main() {
    app.add_plugins(DefaultPlugins)
          .add_systems(Startup, spawn_camera);
}

fn spawn_camera(mut commands: Commands) {
    commands.spawn(Camera2dBundle{
        ..default()
    });
}
```

**Comment by inodentry** [comment]
There is now a detailed page for 2D (and also 3D) camera setup!

**Comment by stevehello166** [comment]
thanks
