### ISSUE TITLE
Plugins guidelines link

### ISSUE THREAD

**Issue by EZSNoVa** [bevy-cheatbook/bevy-cheatbook#263]
Fix broken link: [the official guidelines for plugin authors](https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md)
^^^^ - Points to nowhere

Should point to (I think): https://bevy-cheatbook.github.io/setup/bevy-git.html#advice-for-plugin-authors

At: [Publishing Crates](https://bevy-cheatbook.github.io/programming/plugins.html#publishing-crates)

**Comment by inodentry** [comment]
No, there used to be a page in bevy's GH repo, which is now removed. The correct course of action is to remove the link outright.
