### ISSUE TITLE
don't shorten asset_server to ass

### ISSUE THREAD

**Issue by reoseah** [bevy-cheatbook/bevy-cheatbook#279]
Yes it made me smile, but maybe that's not what you want in documentation.

Here https://github.com/bevy-cheatbook/bevy-cheatbook/blob/fdf50e4cc431e972a290f3e146b3ffa28de7bf36/src/3d/gltf.md?plain=1#L195, contains this:
```rust
let gltf = ass.load("my_asset_pack.glb");
commands.insert_resource(MyAssetPack(gltf));
```

**Comment by inodentry** [comment]
Why not? It's *my* book! ;)
