### ISSUE TITLE
Run Criteria

### ISSUE THREAD

**Issue by jamadazi** [bevy-cheatbook/bevy-cheatbook#3]
Add a section to cover Run Criteria.

**Comment by alice-i-cecile** [comment]
Combining run criteria is particularly tricky, and worth discussing.

**Comment by jamadazi** [comment]
New page to introduce the topic, added to the new 0.5 book.

I could not address combining run criteria, or looping run criteria at this time; this will be left as future work. I'll file new issues for these.
