### ISSUE TITLE
Common Pitfall: using add_system instead of add_startup_system?

### ISSUE THREAD

**Issue by ramirezmike** [bevy-cheatbook/bevy-cheatbook#41]
Mixing up add_system and add_startup_system can cause bugs or performance issues that might not be easy to track down for beginners. This might be a good thing to point out in the [system function common pitfall page](https://bevy-cheatbook.github.io/next/pitfalls/into-system.html)?

**Comment by jamadazi** [comment]
I decided to address this directly in the "Bevy Programming > Basics > Systems" page, alongside mentioning the app builder (as suggested in #40).

I think this is a better place for it. It will lead to more visibility. The "system function pitfall" page you linked is for when people get compiler errors with adding systems, so it didn't feel right to put it there.
