### ISSUE TITLE
Broken link on second place in serp

### ISSUE THREAD

**Issue by RomainMazB** [bevy-cheatbook/bevy-cheatbook#58]
Hi there ✌️

I'm a web developer landing in the Rust's and Bevy's communities.

I don't know if what I'll report is even possible to fix due to that fact that the Rusts books seem to be self-generated but I've searched for "bevy queries" on Google and found a broken link at the second place of the serp, linking to this page:

https://bevy-cheatbook.github.io/cheatsheet/release.html

I have a huge background into web development (10y+) so ask me if my skills can help :)

**Comment by jamadazi** [comment]
This is related to the restructuring of the book around the Bevy 0.5 release. In the old version of the book, I had 2 cheatsheet pages: one covering the release version of bevy, and one that was supposed to cover the latest git main branch.

The git main one was not kept up to date and was largely useless, so I removed it.

Now there is only a single cheatsheet page, located at:

https://bevy-cheatbook.github.io/cheatsheet.html

Perhaps creating some sort of redirect from the old URL to the new one should be the way to go ... but I don't know how to do that, considering that the book is a static site generated with `mdbook` and hosted on GitHub Pages.

**Comment by RomainMazB** [comment]
@jamadazi yeah the right thing to do here is a 302 redirection to tell search engine the ressources moved to another url.

It can be done directly from a .htaccess file on the root directory

Can help you on such things, I'll ping you on Discord to guide you if you want.

**Comment by RomainMazB** [comment]
Ok, I've searched to know more about what GH pages supports and it does not support htaccess file.

Another way to do is to create a file named with the old name and insert some redirection content into it.

See the trick here: https://gist.githubusercontent.com/domenic/1f286d415559b56d725bee51a62c24a7/raw/e7b4ca78fb830325b4bf28d4c2ad8c771564e4bf/redirecting-github-pages.md

**Comment by RomainMazB** [comment]
I've made a quick search to see if more links are having the same issue.

There are more than just one page in google binding to a not found pages: https://www.google.com/search?q=site%3Abevy-cheatbook.github.io&oq=site%3Abevy-cheatbook.github.io&aqs=chrome..69i57j69i58.10679j0j4&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8

I'll made a PR to solve all of them.

With my Rust/Bevy knowledge, I can't add content to the doc, but I can help others to find accurate content with my web experience :)

**Comment by jamadazi** [comment]
Trying the google link above, now, a month later, does not seem to result in any broken links. Google probably took care of it by itself.

I will close this issue and the PR. They don't seem to be needed.
