### ISSUE TITLE
Advanced Pattern: Custom Commands

### ISSUE THREAD

**Issue by inodentry** [bevy-cheatbook/bevy-cheatbook#8]
Add a page to show how to extend `Commands` with custom commands for your game.

See this discord post for reference: https://discord.com/channels/691052431525675048/730525730601041940/813570672110469190

**Comment by alice-i-cecile** [comment]
Definitely needs some caveats about *why* you might want to do this. In many cases, you'll want either local mutation or events instead, but I really love custom commands for when you need to mutate several entities at once.

**Comment by alice-i-cecile** [comment]
For reference, here's a [nice stub](https://github.com/Leafwing-Studios/fop-game/blob/6db6758ae79663e6f495f679a4ef7b09ad289d80/src/core/entity_clone.rs) that I made using this pattern. I found that the `extend::ext` method shown in the screen shot caused serious issues with importing the generated trait across files (and it's generally less clear), so I wouldn't recommend it.
