### ISSUE TITLE
2.1.7. Events confusing for beginner

### ISSUE THREAD

**Issue by dippa-1** [bevy-cheatbook/bevy-cheatbook#94]
As a beginner, I was confused because I could not get events working for a while.

The code in the book only says to add the event to the app builder.
But it wasn't clear for me that the event receiver is a system that must be added too.

Possible fix:
change the second code example to 
```rust
fn main() {
    App::build()
        // ...
        .add_event::<LevelUpEvent>()
        .add_system(debug_levelups.system())
        // ...
        .run();
}
```

**Comment by jamadazi** [comment]
Thanks for reporting this!
