### ISSUE TITLE
Adjust guidance on desktop apps with wasm-pack

### ISSUE THREAD

**Issue by lee-orr** [bevy-cheatbook/bevy-cheatbook#97]
I found that just adding a `main.rs` as described [here]( https://bevy-cheatbook.github.io/platforms/wasm/wasm-pack.html) leads to some inconsistencies - where it works with cargo run, but not necessarily with cargo build. Creating a separate crate for native builds that pulls in the lib file & just has that kind of main.rs resolves that issue.

**Comment by inodentry** [comment]
related to #100

**Comment by inodentry** [comment]
This no longer exists in the book. With 0.6, the WASM chapter has been greatly simplified. :)
