### ISSUE TITLE
Add documentation describing that resolver=2 is necessary

### ISSUE THREAD

**Issue by TheButlah** [bevy-cheatbook/bevy-cheatbook#98]
From https://discord.com/channels/691052431525675048/911894894778396682/911895674977681429

Bevy doesn't seem to work with wasm without resolver=2. Documentation should be added that explains this. Also, it should be noted that resolver is a workspace level feature, so the documentation should also note that it needs to be in your workspace file, if you are using workspaces.

**Comment by TheButlah** [comment]
https://github.com/rust-lang/cargo/issues/10112

**Comment by inodentry** [comment]
relevant in #103

**Comment by inodentry** [comment]
This is now covered in the "strange build errors" page. Seemed like the most appropriate place to put it.

I will also make sure to mention this in any other future pages where it is relevant (like setup guides).
